import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import "../lib/i18n";
import { AuthProvider } from "@/context/AuthContext";
import { ThemeProvider } from "next-themes";
import { InternationalizationProvider } from "@/context/InternationalizationContext";
import TranslationProvider from "@/components/custom/TranslationProvider";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className={`${GeistSans.className} antialiased dark:bg-gray-950`}>
      <ThemeProvider attribute="class">
        <TranslationProvider>
          <InternationalizationProvider>
            <AuthProvider>
              <body>{children}</body>
            </AuthProvider>
          </InternationalizationProvider>
        </TranslationProvider>
      </ThemeProvider>
    </html>
  );
}
